name: MVVM-Combine-SwiftUI
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.example
packages:
  netfox:
    url: https://github.com/kasketis/netfox.git
    from: 1.21.0
targets:
  MVVM-Combine-SwiftUI:
    type: application
    platform: iOS
    sources: [MVVM-Combine-SwiftUI]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MVVM-Combine-SwiftUI
      INFOPLIST_FILE: MVVM-Combine-SwiftUI/Info.plist
    dependencies:
        - package: netfox
  MVVM-Combine-SwiftUI-Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [MVVM-Combine-SwiftUI-Tests]
    dependencies:
      - target: MVVM-Combine-SwiftUI
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MVVM-Combine-SwiftUI.app/MVVM-Combine-SwiftUI"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  MVVM-Combine-SwiftUI:
    build:
      targets:
        MVVM-Combine-SwiftUI: all
        MVVM-Combine-SwiftUI-Tests: all
    test:
        targets:
        - name: MVVM-Combine-SwiftUI-Tests
        gatherCoverageData: true
