name: MVVM-Combine-SwiftUI
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.example
targets:
  MVVM-Combine-SwiftUI:
    type: application
    platform: iOS
    sources: [MVVM-Combine-SwiftUI]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MVVM-Combine-SwiftUI
      INFOPLIST_FILE: MVVM-Combine-SwiftUI/Info.plist
schemes:
  MVVM-Combine-SwiftUI:
    build:
      targets:
        MVVM-Combine-SwiftUI: all